title:               Erosion QLD
url:                 https://www.erosionqld.com.au
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Evan Millwood
  url:               https://www.erosionqld.com.au
  email:             e6e513a3-abdd-49b6-b729-2326f22620e2@anonaddy.me

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist